<a href="https://colab.research.google.com/github/ImTenderFoot/first-repository/blob/main/numpy_array_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy


In [19]:
import numpy as np  #to import numpy

a=np.array([1,2,3]) #to define array we use funtion np.array()
b=np.array([4,5,6])

print(a)    #we can simply print
print(b)    #arrays are not comma saparated
print((a+b))
print(type(a+b))


[1 2 3]
[4 5 6]
<class 'numpy.ndarray'>


In [23]:
#list vs array

list1= [1,2,3,4] #this is list
array1=np.array(list1)#array of this list
print(list1 ,"=",type(list1),"\n", array1,"=",type(array1))


'''list vs array //theory
list has easier to modify add delete etc
list dont directly perform math operations
list can have nested data with diffrent size and data types
[[1,2],[3,4,5]] is ok

array not easier to modify
array use to perform mathematical operations , this is fast
#it dont support multi data type
[[1,2],[3,4,5]] give error cuz it need same num of elements
'''
c=np.array([1,2,'3'])
print(c)
#this convert everything into string cuz array dont support multiple datatype at once

[1, 2, 3, 4] = <class 'list'> 
 [1 2 3 4] = <class 'numpy.ndarray'>
['1' '2' '3']


In [39]:
#Note: use [ ] operators inside numpy.array() for multi-dimensional
#1. Axis: The Axis of an array describes the order of the indexing into the array.
'''
Axis 0 = one dimensional

Axis 1 = Two dimensional

Axis 2 = Three dimensional
'''
#2. Shape: The number of elements along with each axis. It is from a tuple.
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array_3d.shape)

(2, 2, 2)


In [41]:
#what is 2d array exp
d=np.array([[1,2],[3,4]])
e=np.array([[1,2],[3,4]])

print("the addtion of two 2d array is a 2d array",d+e)


#this is 3d array all are correct

array3d=np.array([[[111,222],[333,444],[555,666]]])
print("\nthis is 3d array= ",array3d)
print(array3d.shape)

array3d2=np.array([[[111,222]],[[333,444]],[[555,666]]])
print("\nthis is 3d array= ",array3d2)
print(array3d2.shape)

array3d3=np.array([[[1],[2]],[[4],[6]],[[8],[9]]])
print("\nthis is 3d array= ",array3d3)
print(array3d3.shape)

the addtion of two 2d array is a 2d array [[2 4]
 [6 8]]

this is 3d array=  [[[111 222]
  [333 444]
  [555 666]]]
(1, 3, 2)

this is 3d array=  [[[111 222]]

 [[333 444]]

 [[555 666]]]
(3, 1, 2)

this is 3d array=  [[[1]
  [2]]

 [[4]
  [6]]

 [[8]
  [9]]]
(3, 2, 1)


In [36]:
# qiestion prompt: how to change 3d array and make it a 1d array

# 3D array
array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Flatten the 3D array into a 1D array
array_1d = three_d_array.flatten()

print("Original 3D array:")
print(type(array_3d))
print("\n1D array:")
print(array_1d)


Original 3D array:
<class 'numpy.ndarray'>

1D array:
[1 2 3 4 5 6 7 8]


In [44]:
#3.'rank' of the array is the number of axes/dimentions in array

#4. 'Data type objects' (dtype): Data type objects (dtype) is an instance of
# numpy.dtype class. It describes how the bytes in the fixed-size block of
#memory corresponding to an array item should be interpreted.

arr1=np.array([[23],[23],[23]])
print("data type of aray=",arr1.dtype)

data type of aray= int64


In [45]:
from google.colab import files


uploaded = files.upload()

Saving student.csv to student.csv


In [50]:
import pandas as pd
import io
df=pd.read_csv(io.BytesIO(uploaded['student.csv']))
print(df)

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
2    3       Arnold  Three    55    male
3    4   Krish Star   Four    60  female
4    5    John Mike   Four    60  female
5    6    Alex John   Four    55    male
6    7  My John Rob  Fifth    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
9   10     Big John   Four    55  female
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row   Four    88    male
15  16        Gimmy   Four    88    male
16  17        Tumyu    Six    54    male
17  18        Honny   Five    75    male
18  19        Tinny   Nine    18    male
19  20       Jackly   Nine    65  female
20  21   Babby John   Four    69  female
21  22       Reggid  Seven    55  female
22  23        Herod  Eight    79    male
23  24    Tiddy 